CREATE TABLE MEMBER(
    ID  VARCHAR2(20) CONSTRAINT MEMBER_PK PRIMARY KEY,
    PW VARCHAR(20) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    WIN NUMBER(5),
    LOSE NUMBER(5),
    RDATE DATE
);

CREATE TABLE BOARD(
 NO NUMBER(10) CONSTRAINT BOARD_PK PRIMARY KEY,
 TITLE VARCHAR(40),
 CONTENT VARCHAR(1000),
 ID VARCHAR(20),
 VIEWCOUNT NUMBER(5),
 WDATE DATE,
 CONSTRAINT FK_BOARD FOREIGN KEY (ID) REFERENCES MEMBER(ID)
);

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='MEMBER' OR TABLE_NAME='BOARD';