-- 멤버 테이블 생성
CREATE TABLE MEMBER(
    ID  VARCHAR2(20) CONSTRAINT MEMBER_PK PRIMARY KEY,
    PW VARCHAR(20) NOT NULL,
    WIN NUMBER(5),
    LOSE NUMBER(5),
    RDATE DATE
);

-- 게시판 테이블 생성
CREATE TABLE BOARD(
 NO NUMBER(10) CONSTRAINT BOARD_PK PRIMARY KEY,
 TITLE VARCHAR(40) NOT NULL,
 CONTENT VARCHAR(1000) NOT NULL,
 ID VARCHAR(20) NOT NULL,
 VIEWCOUNT NUMBER(5) NOT NULL,
 WDATE DATE NOT NULL,
 CONSTRAINT FK_BOARD FOREIGN KEY (ID) REFERENCES MEMBER(ID)
);

-- 게시글 번호 시퀀스 생성
CREATE SEQUENCE BOARD_NO_SEQ
START WITH 1
INCREMENT BY 1;
SELECT * FROM USER_SEQUENCES;

-- 계정 생성
INSERT INTO MEMBER VALUES('test', '1234', 0, 0, SYSDATE);
-- 게시글 작성
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL, '제목', '내용', 'test', 0, SYSDATE);

select * from board;